name: 自动更新博客文章到 README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 UTC

permissions:
  contents: write

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Python script to update README
        run: python build_readme.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m "feat: 自动更新最新博客文章 [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
